import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "@/components/ui/toast";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
        <header className="border-b">
          <div className="mx-auto max-w-6xl px-4 py-4 flex items-center justify-between">
            <Link href="/" className="text-xl font-semibold">Grossanzeigen</Link>
            <nav className="flex items-center gap-4 text-sm">
              <Link href="/search" className="hover:underline">Search</Link>
              <Link href="/sell" className="hover:underline">Sell</Link>
              <Link href="/account" className="hover:underline">Account</Link>
            </nav>
          </div>
        </header>
        <main className="flex-1">
          <Providers>{children}</Providers>
        </main>
        <footer className="border-t">
          <div className="mx-auto max-w-6xl px-4 py-6 text-sm text-gray-500">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
              <div>© {new Date().getFullYear()} Grossanzeigen</div>
              <nav className="flex items-center gap-4">
                <Link href="/policies/terms" className="hover:underline">Terms</Link>
                <Link href="/policies/privacy" className="hover:underline">Privacy</Link>
                <Link href="/policies/prohibited-items" className="hover:underline">Prohibited Items</Link>
                <Link href="/policies/community-guidelines" className="hover:underline">Community Guidelines</Link>
              </nav>
            </div>
          </div>
        </footer>
        <ToastContainer />
      </body>
    </html>
  );
}
